# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
variables:
  RUST_IS_LIBRARY: true
  RUST_FEATURE_FLAGS: with_serde collections collections-const-hash-map collections-hash-map collections-simple-linked-list collections-vec-deque common common-all common-try-default common-boxed-future common-ips common-process error error-all error-tracer error-tracer-macros error-type-registry log log-tracing log-tracing-bunyan log-tracing-deeplog log-tracing-syslog log-tracing-macros log-tracing-macros-syslog log-tracing-macros-common net net-hostname path path-dirs rails rails-ext rails-tracing storage storage-all storage-web storage-io storage-yaml-ext storage-json-ext template time time-serde

include:
  - project: ci-cd/rust
    ref: master
    file: collections/complete.yml
  - project: ci-cd/rust
    ref: master
    file: deploy/publish.yml
