use core::fmt::Debug;

pub trait RailsSyslog<T> {
    fn log<L: FnOnce(&T)>(self, o: L) -> Self;
}

impl<T, E> RailsSyslog<Result<T, E>> for Result<T, E> {
    fn log<L: FnOnce(&Result<T, E>)>(self, log: L) -> Self {
        log(&self);
        self
    }
}

#[cfg(test)]
#[cfg(feature = "log-tracing-macros-syslog")]
mod test {
    use super::RailsSyslog;
    use crate::log::tracing::entity::syslog::facility::Facility::*;
    use crate::{
        alert, crit, critical, debug, emerg, emergency, err, error, info, notice, warn, warning,
    };
    use tracing_subscriber::{fmt, EnvFilter};

    #[test]
    fn test_logging_implementation() {
        // Set up a tracing subscriber for logs
        let subscriber = fmt()
            .with_env_filter(EnvFilter::from_default_env())
            .finish();
        tracing::subscriber::set_global_default(subscriber)
            .expect("Failed to set tracing subscriber");

        // Example Result to log
        let res: Result<&str, &str> = Ok("Hello");

        res.log(emergency!(Ok))
            .log(emergency!(Err))
            .log(emergency!(Ok, KernelMessages))
            .log(emergency!(Err, KernelMessages))
            .log(emergency!(Ok, "Hello OK: {}"))
            .log(emergency!(Err, "Hello Error: {}"))
            .log(emergency!(Ok, KernelMessages, "Hello OK: {}"))
            .log(emergency!(Err, KernelMessages, "Hello Error: {}"))
            .log(emerg!(Ok))
            .log(emerg!(Err))
            .log(emerg!(Ok, KernelMessages))
            .log(emerg!(Err, KernelMessages))
            .log(emerg!(Ok, "Hello OK: {}"))
            .log(emerg!(Err, "Hello Error: {}"))
            .log(emerg!(Ok, KernelMessages, "Hello OK: {}"))
            .log(emerg!(Err, KernelMessages, "Hello Error: {}"))
            .log(alert!(Ok))
            .log(alert!(Err))
            .log(alert!(Ok, KernelMessages))
            .log(alert!(Err, KernelMessages))
            .log(alert!(Ok, "Hello OK: {}"))
            .log(alert!(Err, "Hello Error: {}"))
            .log(alert!(Ok, KernelMessages, "Hello OK: {}"))
            .log(alert!(Err, KernelMessages, "Hello Error: {}"))
            .log(critical!(Ok))
            .log(critical!(Err))
            .log(critical!(Ok, KernelMessages))
            .log(critical!(Err, KernelMessages))
            .log(critical!(Ok, "Hello OK: {}"))
            .log(critical!(Err, "Hello Error: {}"))
            .log(critical!(Ok, KernelMessages, "Hello OK: {}"))
            .log(critical!(Err, KernelMessages, "Hello Error: {}"))
            .log(crit!(Ok))
            .log(crit!(Err))
            .log(crit!(Ok, KernelMessages))
            .log(crit!(Err, KernelMessages))
            .log(crit!(Ok, "Hello OK: {}"))
            .log(crit!(Err, "Hello Error: {}"))
            .log(crit!(Ok, KernelMessages, "Hello OK: {}"))
            .log(crit!(Err, KernelMessages, "Hello Error: {}"))
            .log(error!(Ok))
            .log(error!(Err))
            .log(error!(Ok, KernelMessages))
            .log(error!(Err, KernelMessages))
            .log(error!(Ok, "Hello OK: {}"))
            .log(error!(Err, "Hello Error: {}"))
            .log(error!(Ok, KernelMessages, "Hello OK: {}"))
            .log(error!(Err, KernelMessages, "Hello Error: {}"))
            .log(err!(Ok))
            .log(err!(Err))
            .log(err!(Ok, KernelMessages))
            .log(err!(Err, KernelMessages))
            .log(err!(Ok, "Hello OK: {}"))
            .log(err!(Err, "Hello Error: {}"))
            .log(err!(Ok, KernelMessages, "Hello OK: {}"))
            .log(err!(Err, KernelMessages, "Hello Error: {}"))
            .log(warning!(Ok))
            .log(warning!(Err))
            .log(warning!(Ok, KernelMessages))
            .log(warning!(Err, KernelMessages))
            .log(warning!(Ok, "Hello OK: {}"))
            .log(warning!(Err, "Hello Error: {}"))
            .log(warning!(Ok, KernelMessages, "Hello OK: {}"))
            .log(warning!(Err, KernelMessages, "Hello Error: {}"))
            .log(warn!(Ok))
            .log(warn!(Err))
            .log(warn!(Ok, KernelMessages))
            .log(warn!(Err, KernelMessages))
            .log(warn!(Ok, "Hello OK: {}"))
            .log(warn!(Err, "Hello Error: {}"))
            .log(warn!(Ok, KernelMessages, "Hello OK: {}"))
            .log(warn!(Err, KernelMessages, "Hello Error: {}"))
            .log(notice!(Ok))
            .log(notice!(Err))
            .log(notice!(Ok, KernelMessages))
            .log(notice!(Err, KernelMessages))
            .log(notice!(Ok, "Hello OK: {}"))
            .log(notice!(Err, "Hello Error: {}"))
            .log(notice!(Ok, KernelMessages, "Hello OK: {}"))
            .log(notice!(Err, KernelMessages, "Hello Error: {}"))
            .log(notice!(Ok))
            .log(notice!(Err))
            .log(notice!(Ok, KernelMessages))
            .log(notice!(Err, KernelMessages))
            .log(notice!(Ok, "Hello OK: {}"))
            .log(notice!(Err, "Hello Error: {}"))
            .log(notice!(Ok, KernelMessages, "Hello OK: {}"))
            .log(notice!(Err, KernelMessages, "Hello Error: {}"))
            .log(info!(Ok))
            .log(info!(Err))
            .log(info!(Ok, KernelMessages))
            .log(info!(Err, KernelMessages))
            .log(info!(Ok, "Hello OK: {}"))
            .log(info!(Err, "Hello Error: {}"))
            .log(info!(Ok, KernelMessages, "Hello OK: {}"))
            .log(info!(Err, KernelMessages, "Hello Error: {}"))
            .expect("TODO: panic message");

        // Example Result to log
        let res: Result<&str, &str> = Err("Ellorr");

        res.log(emergency!(Ok))
            .log(emergency!(Err))
            .log(emergency!(Ok, KernelMessages))
            .log(emergency!(Err, KernelMessages))
            .log(emergency!(Ok, "Hello OK: {}"))
            .log(emergency!(Err, "Hello Error: {}"))
            .log(emergency!(Ok, KernelMessages, "Hello OK: {}"))
            .log(emergency!(Err, KernelMessages, "Hello Error: {}"))
            .log(emerg!(Ok))
            .log(emerg!(Err))
            .log(emerg!(Ok, KernelMessages))
            .log(emerg!(Err, KernelMessages))
            .log(emerg!(Ok, "Hello OK: {}"))
            .log(emerg!(Err, "Hello Error: {}"))
            .log(emerg!(Ok, KernelMessages, "Hello OK: {}"))
            .log(emerg!(Err, KernelMessages, "Hello Error: {}"))
            .log(alert!(Ok))
            .log(alert!(Err))
            .log(alert!(Ok, KernelMessages))
            .log(alert!(Err, KernelMessages))
            .log(alert!(Ok, "Hello OK: {}"))
            .log(alert!(Err, "Hello Error: {}"))
            .log(alert!(Ok, KernelMessages, "Hello OK: {}"))
            .log(alert!(Err, KernelMessages, "Hello Error: {}"))
            .log(critical!(Ok))
            .log(critical!(Err))
            .log(critical!(Ok, KernelMessages))
            .log(critical!(Err, KernelMessages))
            .log(critical!(Ok, "Hello OK: {}"))
            .log(critical!(Err, "Hello Error: {}"))
            .log(critical!(Ok, KernelMessages, "Hello OK: {}"))
            .log(critical!(Err, KernelMessages, "Hello Error: {}"))
            .log(crit!(Ok))
            .log(crit!(Err))
            .log(crit!(Ok, KernelMessages))
            .log(crit!(Err, KernelMessages))
            .log(crit!(Ok, "Hello OK: {}"))
            .log(crit!(Err, "Hello Error: {}"))
            .log(crit!(Ok, KernelMessages, "Hello OK: {}"))
            .log(crit!(Err, KernelMessages, "Hello Error: {}"))
            .log(error!(Ok))
            .log(error!(Err))
            .log(error!(Ok, KernelMessages))
            .log(error!(Err, KernelMessages))
            .log(error!(Ok, "Hello OK: {}"))
            .log(error!(Err, "Hello Error: {}"))
            .log(error!(Ok, KernelMessages, "Hello OK: {}"))
            .log(error!(Err, KernelMessages, "Hello Error: {}"))
            .log(err!(Ok))
            .log(err!(Err))
            .log(err!(Ok, KernelMessages))
            .log(err!(Err, KernelMessages))
            .log(err!(Ok, "Hello OK: {}"))
            .log(err!(Err, "Hello Error: {}"))
            .log(err!(Ok, KernelMessages, "Hello OK: {}"))
            .log(err!(Err, KernelMessages, "Hello Error: {}"))
            .log(warning!(Ok))
            .log(warning!(Err))
            .log(warning!(Ok, KernelMessages))
            .log(warning!(Err, KernelMessages))
            .log(warning!(Ok, "Hello OK: {}"))
            .log(warning!(Err, "Hello Error: {}"))
            .log(warning!(Ok, KernelMessages, "Hello OK: {}"))
            .log(warning!(Err, KernelMessages, "Hello Error: {}"))
            .log(warn!(Ok))
            .log(warn!(Err))
            .log(warn!(Ok, KernelMessages))
            .log(warn!(Err, KernelMessages))
            .log(warn!(Ok, "Hello OK: {}"))
            .log(warn!(Err, "Hello Error: {}"))
            .log(warn!(Ok, KernelMessages, "Hello OK: {}"))
            .log(warn!(Err, KernelMessages, "Hello Error: {}"))
            .log(notice!(Ok))
            .log(notice!(Err))
            .log(notice!(Ok, KernelMessages))
            .log(notice!(Err, KernelMessages))
            .log(notice!(Ok, "Hello OK: {}"))
            .log(notice!(Err, "Hello Error: {}"))
            .log(notice!(Ok, KernelMessages, "Hello OK: {}"))
            .log(notice!(Err, KernelMessages, "Hello Error: {}"))
            .log(notice!(Ok))
            .log(notice!(Err))
            .log(notice!(Ok, KernelMessages))
            .log(notice!(Err, KernelMessages))
            .log(notice!(Ok, "Hello OK: {}"))
            .log(notice!(Err, "Hello Error: {}"))
            .log(notice!(Ok, KernelMessages, "Hello OK: {}"))
            .log(notice!(Err, KernelMessages, "Hello Error: {}"))
            .log(info!(Ok))
            .log(info!(Err))
            .log(info!(Ok, KernelMessages))
            .log(info!(Err, KernelMessages))
            .log(info!(Ok, "Hello OK: {}"))
            .log(info!(Err, "Hello Error: {}"))
            .log(info!(Ok, KernelMessages, "Hello OK: {}"))
            .log(info!(Err, KernelMessages, "Hello Error: {}"))
            .ok();
    }
}
